prgrms-web-devcourse-final-project/WEB4_5_ServerSOS_BE

backend/src/main/java/com/pickgo/global/entity/BaseEntity.java, backend/src/main/java/com/pickgo/global/response/RsData.java
> ex) #이슈번호
#3 
- BaseEntity modifiedAt으로 이름 변경
- RsData json ignore 추가
=> chore: BaseEntity 필드 수정, RsData Json ignore 설정

backend/src/main/java/com/pickgo/domain/auth/controller/TokenController.java, backend/src/main/java/com/pickgo/domain/auth/dto/CreateTokenResponse.java, backend/src/main/java/com/pickgo/domain/auth/dto/TokenDetailResponse.java, backend/src/main/java/com/pickgo/domain/auth/service/TokenService.java, backend/src/main/java/com/pickgo/domain/member/controller/MemberController.java, backend/src/main/java/com/pickgo/domain/member/dto/MemberPrincipal.java, backend/src/main/java/com/pickgo/domain/member/dto/MemberUpdateRequest.java, backend/src/main/java/com/pickgo/domain/member/entity/Member.java, backend/src/main/java/com/pickgo/domain/member/service/MemberService.java, backend/src/main/java/com/pickgo/global/jwt/JwtProvider.java, backend/src/test/java/com/pickgo/admin/AdminControllerTest.java, backend/src/test/java/com/pickgo/jwt/JwtProviderTest.java, backend/src/test/java/com/pickgo/member/MemberControllerTest.java, backend/src/test/java/com/pickgo/member/MemberServiceTest.java, backend/src/test/java/com/pickgo/token/TestToken.java, backend/src/test/java/com/pickgo/token/TokenControllerTest.java, backend/src/test/java/com/pickgo/token/TokenServiceTest.java
> ex) #이슈번호
#15 
- 내 정보 수정 API 구현
- 파일 경로 변경
- 기타 리팩토링
=> 회원관리 추가 구현 및 리팩토링

backend/src/main/java/com/pickgo/global/config/SwaggerConfig.java
=> chore: API 명세 버전 추가

backend/src/main/java/com/pickgo/global/s3/S3Config.java
=> fix: 기본값 설정

backend/src/main/java/com/pickgo/global/s3/S3Config.java
=> fix: s3 credential 세팅 수정

backend/src/main/java/com/pickgo/domain/performance/service/PerformanceService.java, backend/src/main/java/com/pickgo/domain/performance/util/PerformanceMapper.java, backend/src/main/java/com/pickgo/domain/venue/entity/Venue.java, backend/src/main/java/com/pickgo/global/init/BaseInitData.java, backend/src/test/java/com/pickgo/global/init/TestDataInit.java
close #46
- 좌석이 중복 저장되던 오류 해결
- kopis api 호출에 멀티 쓰레딩 적용
멀티쓰레딩 적용 전
멀티쓰레딩 적용 후
=> 초기 데이터 세팅 리팩토링

backend/src/main/java/com/pickgo/domain/admin/controller/AdminPostController.java, backend/src/main/java/com/pickgo/domain/kopis/service/KopisService.java, backend/src/main/java/com/pickgo/domain/member/repository/MemberRepository.java, backend/src/main/java/com/pickgo/domain/member/service/MemberService.java, backend/src/main/java/com/pickgo/domain/performance/entity/PerformanceSession.java, backend/src/main/java/com/pickgo/domain/performance/service/PerformanceService.java, backend/src/main/java/com/pickgo/domain/performance/util/PerformanceMapper.java, backend/src/main/java/com/pickgo/domain/post/post/service/PostService.java, backend/src/main/java/com/pickgo/domain/post/review/controller/PostReviewController.java, backend/src/main/java/com/pickgo/global/init/BaseInitData.java, backend/src/main/resources/application-dev.yml, backend/src/main/resources/application-prod.yml, backend/src/test/java/com/pickgo/global/init/TestDataInit.java, backend/src/test/java/com/pickgo/payment/PaymentControllerTest.java
> ex) #68 
* BaseInitData에 초기 유저 추가
* PerformanceSession에 공연 예매 시작일 추가(공연 시작 30일전)
* Swagger API 겹치는 이름 안겹치게
* 글 작성 부분 createPostPublished 추가 후 사용
* 예매 시작일 Session 생성에 추가
* Venue 중복 저장 오류 수정
=> [refactor] 간단한 작업

backend/src/main/resources/application-prod.yml
=> [!HOTIFX] 운영 전까지는 ddl-auto: create로 유지

backend/src/main/resources/application-prod.yml
=> [!HOTIFX] 운영 전까지는 ddl-auto: create로 유지 (#79)

backend/src/main/java/com/pickgo/domain/performance/service/PerformanceService.java
=> [refactor] venue 저장 로직 검증 추가

backend/src/main/java/com/pickgo/domain/area/area/service/PerformanceAreaService.java
=> fix: getAreas 트랜잭션 처리

backend/build.gradle, backend/docker-compose.yml, backend/src/main/java/com/pickgo/domain/log/dto/ReservationLogResponse.java, backend/src/main/java/com/pickgo/domain/log/entity/AccessHistory.java, backend/src/main/java/com/pickgo/domain/log/entity/ExceptionHistory.java, backend/src/main/java/com/pickgo/domain/log/entity/ReservationHistory.java, backend/src/main/java/com/pickgo/domain/log/enums/ActionType.java, backend/src/main/java/com/pickgo/domain/log/repository/AccessHistoryRepository.java, backend/src/main/java/com/pickgo/domain/log/repository/ExceptionLogRepository.java, backend/src/main/java/com/pickgo/domain/member/admin/controller/AdminMonitoringController.java, backend/src/main/java/com/pickgo/global/config/SecurityConfig.java, backend/src/main/java/com/pickgo/global/jwt/JwtAuthenticationFilter.java, backend/src/main/java/com/pickgo/global/logging/aspect/AccessLogAspect.java, backend/src/main/java/com/pickgo/global/logging/service/HistorySaveService.java, backend/src/main/java/com/pickgo/global/logging/util/LogWriter.java, backend/src/main/resources/templates/admin/monitoring.html, infra/main.tf
> ex) #102 
* AccessHistory -> 모든 api 에 대한 접근 통계용 엔티티
* ReservationHistory 에 컬럼 추가(배포전 drop-create)
* grafana 도커 추가 및 배포 완료
* 로컬에서는 아래와같이 테스트 완료 배포후에 수정 필요할 수도 있음
=> 로그 리펙토링 및 그라파나 도커 컴포즈에 추가

frontend/src/api/__generated__/models/BaseLogResponse.ts, frontend/src/api/__generated__/models/JspPropertyGroupDescriptor.ts, frontend/src/api/__generated__/models/ReservationLogResponse.ts, frontend/src/hooks/useSubscriptionEnterQueue.ts, frontend/src/lib/subscribeSSE.ts, frontend/src/pages/Login.tsx, frontend/src/pages/ShowDetail.tsx, frontend/src/pages/ShowReservation.tsx
=> [Frontend] 대기열처리

backend/src/main/java/com/pickgo/domain/post/review/controller/PostReviewController.java
=> fix: API 명 수정

backend/docker-compose-metric.yml, backend/docker-compose.yml, backend/prometheus.yml, backend/src/main/resources/templates/admin/monitoring.html, infra/main.tf
=> 서버 분리에 따른 코드 변경 

backend/build.gradle, backend/docker-compose-metric.yml, backend/docker-compose.yml, backend/prometheus.yml, backend/src/main/java/com/pickgo/PickgoApplication.java, backend/src/main/java/com/pickgo/domain/member/admin/service/AdminPostService.java, backend/src/main/java/com/pickgo/domain/post/post/controller/PostController.java, backend/src/main/java/com/pickgo/domain/post/post/service/PostService.java, backend/src/main/java/com/pickgo/global/config/RedisConfig.java, backend/src/main/resources/templates/admin/monitoring.html, infra/main.tf
=> 메인 머지 및 배포

backend/docker-compose.yml, backend/src/main/resources/application.yml, infra/main.tf
=> [!HOTFIX] 레디스 설정

.github/workflows/pull-request-ci.yml, backend/src/main/java/com/pickgo/global/config/RedisConfig.java, backend/src/main/resources/application-prod.yml, backend/src/main/resources/application.yml, infra/main.tf
* [chore] redis 포트 막기, 나머지 열여두기
* [chore] ci test에 redis password 추가
* [chore] RedisConfig에 비밀번호 추가
* [chore] 배포서버에서만 비번 작동하도록 변경
=> 배포서버 레디스 비번 적용

frontend/src/components/reservation/SeatMap.tsx, frontend/src/hooks/useAreas.ts, frontend/src/hooks/useReservation.ts, frontend/src/pages/PaymentPage.tsx, frontend/src/pages/ShowReservation.tsx
=> [Frontend]: EntryAuth 반영

frontend/src/components/reservation/SeatMap.tsx, frontend/src/pages/PaymentPage.tsx
=> [Frontend] reservation index 이슈 해결

frontend/src/components/reservation/SeatMap.tsx
=> [Frontend]: reservedSeats에도 index 이슈 해결

backend/src/main/java/com/pickgo/domain/queue/policy/EntryCountDecider.java, backend/src/main/java/com/pickgo/domain/queue/scheduler/QueueProcessorScheduler.java, backend/src/main/java/com/pickgo/global/infra/metric/repository/redis/RedisMetricRepository.java, backend/src/main/java/com/pickgo/global/infra/metric/scheduler/MetricScheduler.java, backend/src/test/java/com/pickgo/domain/queue/scheduler/QueueProcessorSchedulerTest.java
#147 
- 스프링 액추에이터를 통해 TPS를 측정 및 redis에 저장
- 트래픽 대비 입장 인원 수 결정(선형보간법)
- 대기열 스케줄러에 반영
=> [feat] 트래픽 기반 입장 인원 수 조절

frontend/src/App.tsx, frontend/src/components/category/constants.ts, frontend/src/components/show/ShowList.tsx, frontend/src/hooks/usePosts.ts, frontend/src/pages/EditProfile.tsx, frontend/src/pages/My.tsx, frontend/src/pages/MyReservationList.tsx, frontend/src/pages/ReservationDetailModal.tsx
close #157
- 내 정보 수정 페이지 구현 (닉네임 변경, 비밀번호 변경, 회원 탈퇴)
- 예매 목록 페이지에서 예매 상세 모달 구현
- 예매 목록에서 예매자 정보는 제거 했습니다. 어짜피 본인이기 때문에 필요없을 듯 하여
- 공연 목록 페이지에서 검색 기능 구현
=> 마이페이지 관련 기능 구현

backend/build.gradle, backend/src/main/java/com/pickgo/global/infra/limiter/IpRateLimitingFilter.java, backend/src/main/java/com/pickgo/global/response/RsCode.java, backend/src/main/java/com/pickgo/global/response/RsConstant.java
#170 
- ip 확인 및 API 호출 rate 검증 필터 구현
- rate limiter 관련 설정
- 우선 구역 및 좌석 조회에만 적용했습니다.
=> [feat] Rate Limiter 적용

backend/build.gradle, backend/src/main/java/com/pickgo/domain/auth/token/controller/TokenController.java, backend/src/main/java/com/pickgo/domain/auth/token/repository/redis/RedisRefreshTokenRepository.java, backend/src/main/java/com/pickgo/domain/auth/token/service/TokenService.java, backend/src/main/java/com/pickgo/domain/member/member/service/MemberService.java, backend/src/main/java/com/pickgo/global/infra/limiter/IpRateLimitingFilter.java, backend/src/main/java/com/pickgo/global/infra/server/redis/RedisServerRegistry.java, backend/src/main/java/com/pickgo/global/response/RsCode.java, backend/src/main/java/com/pickgo/global/response/RsConstant.java, backend/src/test/java/com/pickgo/domain/auth/auth/controller/TokenControllerTest.java, backend/src/test/java/com/pickgo/domain/auth/auth/service/TokenServiceTest.java, backend/src/test/java/com/pickgo/domain/member/member/controller/MemberControllerTest.java, backend/src/test/java/com/pickgo/domain/member/member/service/MemberServiceTest.java
#172 
- refreshToken redis에 저장
- 액세스 토큰 재발급 시 redis에서 refreshToken 조회 및 검증
=> [feat] 인증 시 RTR 방식 적용

frontend/src/components/reservation/SeatMap.tsx
> #179 
- 다른 섹션 선택 가능 하도록 수정
- 다이얼로그의 확인을 눌러야 반영이 되도록 수정
- SSE 연결을 통한 실시간 좌석 상태 조회는 아직 구현 중 입니다. 완료 시 따로 PR 올리겠습니다
=> feat: 좌석 이슈 수정

frontend/src/pages/ShowDetail.tsx
=> [FE] 게시글 조회수 보이게 설정

backend/build.gradle, backend/src/main/java/com/pickgo/domain/auth/token/controller/TokenController.java, backend/src/main/java/com/pickgo/domain/auth/token/repository/redis/RedisRefreshTokenRepository.java, backend/src/main/java/com/pickgo/domain/auth/token/service/TokenService.java, backend/src/main/java/com/pickgo/domain/member/member/service/MemberService.java, backend/src/main/java/com/pickgo/global/infra/limiter/IpRateLimitingFilter.java, backend/src/main/java/com/pickgo/global/infra/server/redis/RedisServerRegistry.java, backend/src/main/java/com/pickgo/global/response/RsCode.java, backend/src/main/java/com/pickgo/global/response/RsConstant.java, backend/src/test/java/com/pickgo/domain/auth/auth/controller/TokenControllerTest.java, backend/src/test/java/com/pickgo/domain/auth/auth/service/TokenServiceTest.java, backend/src/test/java/com/pickgo/domain/member/member/controller/MemberControllerTest.java, backend/src/test/java/com/pickgo/domain/member/member/service/MemberServiceTest.java, frontend/src/components/reservation/SeatMap.tsx, frontend/src/pages/Join.tsx, frontend/src/pages/ShowDetail.tsx
=>  develop -> main 배포
